# Generated by Django 6.0.7 on 2026-08-31 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0002_claveproducto'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntregaClave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True)),
                ('clave_producto', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='publicaciones.claveproducto', verbose_name='Clave Asignada')),
                ('detalle_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claves_entregadas', to='ventas.detallepedido')),
            ],
        ),
    ]
