# Generated by Django 6.0.7 on 2026-07-30 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContenidoDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_zip', models.FileField(blank=True, help_text='Archivo .zip del juego para adjuntar en correo', null=True, upload_to='juegos_zips/')),
                ('url_drive', models.URLField(blank=True, help_text='Enlace alternativo de Google Drive/Mega si el archivo es muy pesado', null=True)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contenido_digital', to='publicaciones.producto')),
            ],
        ),
    ]
