# Generated by Django 6.0.7 on 2026-07-29 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título del Banner')),
                ('subtitulo', models.CharField(blank=True, max_length=255, verbose_name='Subtítulo')),
                ('imagen', models.ImageField(upload_to='banners/', verbose_name='Imagen Promocional')),
                ('url_destino', models.CharField(blank=True, default='#', max_length=255, verbose_name='Enlace de destino')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Está activo?')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Banner Promocional',
                'verbose_name_plural': 'Banners Promocionales',
                'ordering': ['orden', '-creado_el'],
            },
        ),
    ]
