# Generated by Django 6.0.7 on 2026-08-31 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaveProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=100, unique=True, verbose_name='Código de Activación / Key')),
                ('disponible', models.BooleanField(default=True, verbose_name='¿Está disponible para venta?')),
                ('fecha_agregada', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claves', to='publicaciones.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Clave de Producto',
                'verbose_name_plural': 'Claves de Productos',
            },
        ),
    ]
